import{a as B,S as h,i as l}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const f of n.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&s(f)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const I="42660522-ae3104db13d278f91a0482c47";async function y(t,e=1,r=15){try{return(await B.get(`https://pixabay.com/api/?key=${I}&q=${t}&page=${e}&per_page=${r}`)).data}catch(s){throw console.error("Error fetching data:",s),s}}const b=document.getElementById("loader"),$=document.getElementById("gallery"),P=new h(".gallery a"),m=document.getElementById("loadMoreBtn");function g(t,e){if(e&&(b.style.display="none"),t.length===0){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}t.forEach(r=>{const s=document.createElement("div");s.classList.add("card"),s.innerHTML=`
            <a href="${r.largeImageURL}" data-lightbox="gallery">
                <img src="${r.webformatURL}" alt="${r.tags}">
            </a>
            <p>Likes: ${r.likes}</p>
            <p>Views: ${r.views}</p>
            <p>Comments: ${r.comments}</p>
            <p>Downloads: ${r.downloads}</p>
        `,$.appendChild(s)}),P.refresh()}function a(){m.style.display="none"}function v(){m.style.display="block"}function i(){l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const O=document.getElementById("loader"),M=document.getElementById("gallery");new h(".gallery a");const A=document.getElementById("loadMoreBtn"),S=document.getElementById("searchForm"),p=document.getElementById("searchInput"),E="block",L="none",D=15;function u(t){O.style.display=t}let c=1,d=!1;S.addEventListener("submit",async function(t){t.preventDefault();const e=p.value.trim();if(e===""){l.error({title:"Error",message:"Please enter a search term"});return}u(E),M.innerHTML="",c=1,d=!1;try{const r=await y(e,c);g(r.hits,!0),r.hits.length===0?(a(),i()):(v(),w())}catch(r){console.error("Error fetching data:",r),l.error({title:"Error",message:"An error occurred while fetching data. Please try again."})}finally{u(L)}});A.addEventListener("click",async function(){c++;try{if(d){a(),i();return}const t=p.value.trim();u(E);const e=await y(t,c);!e.hits||e.hits.length===0?(d=!0,a(),i()):(g(e.hits,!1),w()),e.totalHits<=c*D&&(d=!0,a(),i())}catch(t){console.error("Error fetching data:",t),l.error({title:"Error",message:"An error occurred while fetching more data. Please try again."})}finally{u(L)}});function w(){const t=document.querySelectorAll(".card");if(t.length>0){const e=t[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
